- name: restart nginx
  become: yes
  systemd:
    name: nginx
    state: restarted

- name: restart mysql
  become: yes
  systemd:
    name: mariadb
    state: restarted

- name: restart php-fpm
  become: yes
  systemd:
    name: pgp-fpm
    state: restarted