- name: Install MariaDB
  become: true
  import_tasks: mariadb.yml
  tags:
    - mariadb

- name: Install Nextcloud
  import_tasks: nextcloud.yml
  tags:
    - nextcloud

- name: Install Nginx
  import_tasks: nginx.yml
  tags:
    - nginx