- name: Install MariaDB packages
  pacman:
    name: "{{ item }}"
  with_items:
    - mariadb
    - mariadb-clients

- name: Run mysql_install_db
  shell: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql

- name: Enabled and start mariadb
  systemd:
    name: mariadb
    enabled: true
    state: started

# We could use 'expect' to run mysql_secure_installation, but this seems simpler
- name: Secure MySQL installation
  shell: |
    mysqladmin -u root password "{{ mysql_root_pass }}"
    mysql -u root -p"{{ mysql_root_pass }}" -e "UPDATE mysql.user SET Password=PASSWORD('{{ mysql_root_pass }}') WHERE User='root'"
    mysql -u root -p"{{ mysql_root_pass }}" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    mysql -u root -p"{{ mysql_root_pass }}" -e "DELETE FROM mysql.user WHERE User=''"
    mysql -u root -p"{{ mysql_root_pass }}" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    mysql -u root -p"{{ mysql_root_pass }}" -e "FLUSH PRIVILEGES"
  changed_when: false

# Ansible mysql modules need too many dependencies (pip, gcc etc.). Therefore, run from shell.
- name: Create 'nextcloud' database
  shell: mysql -u root -p"{{ mysql_root_pass }}" -e "CREATE DATABASE IF NOT EXISTS nextcloud DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
  changed_when: false

- name: Create 'nextcloud' user
  shell: mysql -u root -p"{{ mysql_root_pass }}" -e "CREATE USER IF NOT EXISTS nextcloud@localhost IDENTIFIED BY 'password';"
  changed_when: false

- name: Grant privilages to 'nextcloud' user
  shell: mysql -u root -p"{{ mysql_root_pass }}" -e "GRANT ALL PRIVILEGES ON nextcloud.* TO nextcloud@localhost;"
  changed_when: false
